// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1X1Sn9zxJpBiRtXXlLBtDsKPOCjYA7yU',
    appId: '1:702710209702:web:d662de97bae378e820e867',
    messagingSenderId: '702710209702',
    projectId: 'fir-6c719',
    authDomain: 'fir-6c719.firebaseapp.com',
    storageBucket: 'fir-6c719.appspot.com',
    measurementId: 'G-V94LEVXP6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP8DVpUqCZd_VHe6zFv5wHcGktORlxFzc',
    appId: '1:702710209702:android:42e3ecb2dddacd2120e867',
    messagingSenderId: '702710209702',
    projectId: 'fir-6c719',
    storageBucket: 'fir-6c719.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4syf703rBt6tYOfeY_gCGrUg52puhEHI',
    appId: '1:702710209702:ios:f28ce76c2d74ea2520e867',
    messagingSenderId: '702710209702',
    projectId: 'fir-6c719',
    storageBucket: 'fir-6c719.appspot.com',
    iosClientId: '702710209702-58fb6nqlqn687luvcljqtro1mqu432uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4syf703rBt6tYOfeY_gCGrUg52puhEHI',
    appId: '1:702710209702:ios:f28ce76c2d74ea2520e867',
    messagingSenderId: '702710209702',
    projectId: 'fir-6c719',
    storageBucket: 'fir-6c719.appspot.com',
    iosClientId: '702710209702-58fb6nqlqn687luvcljqtro1mqu432uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.home',
  );
}
